# -*- coding: utf-8 -*-
"""수요포인트.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_d8CRjOOCAADy6zAXsfIdPl8Z7ngTEXA
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df1 = pd.read_excel('/content/drive/MyDrive/bus.xlsx')

df2 = pd.read_excel('/content/drive/MyDrive/중랑구_버스정류소(통합0).xlsx')

df1.info()

df2.info()

df = pd.merge(df1, df2, left_on='버스정류장ARS번호', right_on='정류소번호', how='inner')

df1

df.info()

# 승하차 합 변수 생성
df['승하차 합'] = df['승차총승객수'] + df['하차총승객수']

# 정류장 별로 노선의 개수와 승하차 인원 수 계산, X좌표와 Y좌표 포함
route_and_passenger_counts = df.groupby(['정류소명', 'X좌표', 'Y좌표','행정동']).agg(
    노선_개수=('노선명', 'nunique'),
    총_승하차_인원=('승하차 합', 'sum')
).reset_index()


# 오름차순으로 정렬
route_and_passenger_counts_sorted = route_and_passenger_counts.sort_values(by='총_승하차_인원', ascending=False)

route_and_passenger_counts_sorted

result_file_path = '/content/drive/MyDrive/result2.xlsx'
route_and_passenger_counts_sorted.to_excel(result_file_path, index=False)

top_100_stops = route_and_passenger_counts_sorted.nlargest(100, '총_승하차_인원')

import pandas as pd
import matplotlib.pyplot as plt


# 정류소별 총 승하차 인원 계산
station_totals = route_and_passenger_counts_sorted.groupby('정류소명')['총_승하차_인원'].sum().reset_index()

# 히스토그램 그리기
plt.figure(figsize=(15, 8))
plt.bar(station_totals['정류소명'], station_totals['총_승하차_인원'])
plt.title('Total 승하차 합 per Station')
plt.xlabel('정류소명')
plt.ylabel('총 승하차 인원')
plt.xticks(rotation=90)  # x축 레이블이 겹치지 않도록 회전
plt.grid(True)
plt.show()

top_100_stops



!pip install folium pandas

import folium

# 중심 좌표 설정 (평균값 사용)
center_lat = top_100_stops['Y좌표'].mean()
center_lon = top_100_stops['X좌표'].mean()

# 지도 생성
m = folium.Map(location=[center_lat, center_lon], zoom_start=12)

# 정류장 위치에 마커 추가
for idx, row in top_100_stops.iterrows():
    folium.CircleMarker(
        location=[row['Y좌표'], row['X좌표']],
        radius=5,
        popup=f"{row['정류소명']}<br>총_승하차_인원: {row['총_승하차_인원']}",
        color='blue',
        fill=True,
        fill_color='blue'
    ).add_to(m)

# 지도 표시 및 저장
m.save('/content/top_100_stops_map.html')
m

from google.colab import files
files.download('/mnt/data/top_100_stops_map.html')